modLoader="javafml"
loaderVersion="[0,)"
license="MIT"

[[mods]]
modId="debugkeybind"
version="${version}"
displayName="DebugKeybind"
authors="Boxadactle"
description='''A basic mod that adds keybinds for the F3 menu'''
logoFile='icon.png'

[[dependencies.debugkeybind]]
modId="forge"
mandatory=true
versionRange="[0,)"
ordering="NONE"
side="BOTH"

[[dependencies.debugkeybind]]
modId="minecraft"
mandatory=true
versionRange="[1.15,)"
ordering="NONE"
side="BOTH"

[[dependencies.debugkeybind]]
modId="boxlib"
mandatory=true
versionRange="[3.0.0,4.0.0)"
ordering="NONE"
side="CLIENT"