# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.16.1
loader_version=0.16.14
loom_version=1.11-SNAPSHOT

# Mod Properties
mod_version=3.161.1
maven_group=dev.boxadactle
archives_base_name=debugkeybind

# Dependencies
fabric_version=0.42.0+1.16
modmenu_version = 1.14.15
boxlib_version = 0.161.1-snapshot

#publishing
game_versions = 1.16.1,1.16
project_id_curseforge = 901782
project_id_modrinth = DX9ioka8