# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod properties
mod_version = 12.0.0
maven_group = dev.boxadactle
archives_name = DebugKeybind
enabled_platforms = fabric,forge,neoforge

# Minecraft properties
minecraft_version = 1.21.1

# Dependencies
fabric_loader_version = 0.15.11
fabric_api_version = 0.102.1+1.21.1
neoforge_version = 21.1.6
forge_version = 52.0.4

modmenu_version = 11.0.1
boxlib_version = 14.3.0

#publishing
game_versions = 1.21.1,1.21
project_id_curseforge = 901782
project_id_modrinth = DX9ioka8
release_type = release
changelog_file = CHANGELOG.md