# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod properties
mod_version = 3.1.0
maven_group = dev.boxadactle
archives_name = DebugKeybind
enabled_platforms = fabric,forge

# Minecraft properties
minecraft_version = 1.16.5

# Dependencies
fabric_loader_version = 0.15.11
fabric_api_version = 0.42.0+1.16
forge_version = 36.2.42

modmenu_version = 1.16.23
boxlib_version = 4.0.2

#publishing
game_versions = 1.16.5
project_id_curseforge = 901782
project_id_modrinth = DX9ioka8
release_type = release
changelog_file = CHANGELOG.md