modLoader="javafml"
loaderVersion="${neoforge_loader_version_range}"
license="MIT"

[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
authors="${mod_author}"
description='''${description}'''
logoFile='icon.png'

[[dependencies.${mod_id}]]
   modId="neoforge"
   mandatory=true
   versionRange="${neoforge_loader_version_range}"
   ordering="NONE"
   side="BOTH"

[[dependencies.${mod_id}]]
   modId="minecraft"
   mandatory=true
   versionRange="${minecraft_version_range}"
   ordering="NONE"
   side="BOTH"

[[dependencies.${mod_id}]]
   modId = "boxlib"
   type = "required"
   versionRange = "${boxlib_version_range}"
   ordering = "NONE"
   side = "BOTH"

[[mixins]]
   config = "debugkeybind.mixins.json"