modLoader="javafml"
loaderVersion="[2,)"
license="MIT"

[[mods]]
modId="debugkeybind"
version="${version}"
displayName="DebugKeybind"
logoFile="icon.png"
description='''
A basic mod that adds keybinds for the F3 menu
'''

[[dependencies.debugkeybind]]
   modId="neoforge"
   mandatory=true
   versionRange="[20,)"
   ordering="NONE"
   side="BOTH"

[[dependencies.debugkeybind]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.21.2,)"
   ordering="NONE"
   side="BOTH"

[[dependencies.debugkeybind]]
   modId = "boxlib"
   type = "required"
   versionRange = "[15.0.0, 16.0.0)"
   ordering = "NONE"
   side = "BOTH"

[[mixins]]
   config = "debugkeybind.mixins.json"